# 🎯 WALDOCOIN XRPL TOKEN METADATA
# Must be hosted at: https://waldocoin.live/.well-known/xrp-ledger.toml

[METADATA]
modified_date = "2025-08-24"  # bump when updating to refresh caches

[[CURRENCIES]]
code = "WLO"
issuer = "rstjAWDiqKsUMhHqiJShRSkuaZ44TXZyDY"
name = "WALDOcoin"
display_decimals = 6

# Short, wallet-friendly description
desc = "Meme-to-earn token on XRPL. Create viral memes, earn WALDO."

# Icon should be a small PNG (ideally <=100KB, 64–128px). Replace with a smaller asset when available.
icon = "https://waldocoin.live/wp-content/uploads/waldo-token-logo.png"

# Optional helpers (some indexers use these when Domain is set on-ledger)
website = "https://waldocoin.live"
whitepaper = "https://waldocoin.live/white-paper-waldocoin"
twitter = "https://x.com/W_A_L_D_O_coin"
telegram = "https://t.me/WALDOCOINxrp"
extended_metadata = "https://waldocoin.live/.well-known/waldocoin-metadata.json"

# Optional supply fields (some explorers display these)
max_supply = "1000000000"
total_supply = "976849999"
circulating_supply = "976849999"

# Note: Most wallets require the issuer account's on-ledger Domain to match
# this host (waldocoin.live) to attach metadata automatically.
